name: CI

on: [push, pull_request]

env:
  JULIA_PKG_SERVER:
  PYTHON:

jobs:
  test:
    timeout-minutes: 40
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.10', '1', 'pre']
        arch: [x64]
        os: [ubuntu-latest]
        makie-version: ['0.22', '0.24']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - run: julia -e 'using Pkg; pkg"add Makie@${{ matrix.makie-version }}"'
      - uses: julia-actions/julia-runtest@v1
